name: Run python API tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  generate-api-spec:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Generate open api spec
      run: python3 src/get_api_spec.py

  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: pytest --html=report.html --self-contained-html -vv
    
    # store html test report
    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: html-report
        path: ./report.html  